# Generated by Django 4.2.3 on 2023-08-01 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
