# Generated by Django 4.2.3 on 2023-08-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="weight_kg",
            field=models.FloatField(),
        ),
    ]
