# Generated by Django 4.2.3 on 2023-08-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_weight_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="goal_ml",
            field=models.FloatField(default=0),
        ),
    ]
