# Generated by Django 4.2.3 on 2023-08-01 17:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "goal_of_the_day_ml",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "remaining_goals_ml",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "goal_consumed_ml",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "goal_consumed_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
