# Generated by Django 4.2.3 on 2023-08-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0002_alter_goals_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="goal_consumed_ml",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="goals",
            name="goal_consumed_percentage",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="goals",
            name="goal_of_the_day_ml",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="goals",
            name="remaining_goals_ml",
            field=models.FloatField(),
        ),
    ]
