# Generated by Django 4.2.3 on 2023-08-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0003_alter_goals_goal_consumed_ml_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="goal_consumed_ml",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="goals",
            name="goal_consumed_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="goals",
            name="remaining_goals_ml",
            field=models.FloatField(default=0),
        ),
    ]
