# Generated by Django 4.2.3 on 2023-08-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0004_alter_goals_goal_consumed_ml_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="remaining_goals_ml",
            field=models.FloatField(),
        ),
    ]
