# Generated by Django 4.2.3 on 2023-08-02 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0005_alter_goals_remaining_goals_ml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="goal_consumed_ml",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="goals",
            name="goal_consumed_percentage",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="goals",
            name="goal_of_the_day_ml",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
