# Generated by Django 4.2.3 on 2023-08-02 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0007_remove_goals_created_at_goals_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="remaining_goals_ml",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
