# Generated by Django 4.2.3 on 2023-08-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0008_alter_goals_remaining_goals_ml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
