# Generated by Django 4.2.3 on 2023-08-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0009_alter_goals_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="date",
            field=models.DateField(),
        ),
    ]
